name: widgetlibrary
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_material_showcase: ^1.0.0
  intl: ^0.15.8
  clippy_flutter: ^1.0.0
  carousel_slider: ^1.3.0
  font_awesome_flutter: ^8.5.0
  flutter_circular_slider: ^2.5.0
  rect_getter: ^0.0.1
  gradient_text: ^1.0.2
  http: ^0.12.0+1
  flutter_screenutil: ^0.4.2
  flutter_slidable: ^0.5.4
  dio:
  rxdart:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/middle_travel_ui/
    - assets/images/story_app/
    - assets/images/onboarding/
    - assets/images/onboarding2/
    - assets/images/save_animals/
    - assets/images/bicycle_app/
    - assets/images/tattoo_app/
    - assets/images/adidas_app/
    - assets/images/login/
    - assets/images/streaming_app/
    - assets/images/notes_app/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
          style: italic
    - family: SF-Pro-Text-Regular
      fonts:
        - asset: fonts/SF-Pro-Text-Regular.otf
    - family: SF-Pro-Text-Bold
      fonts:
        - asset: fonts/SF-Pro-Text-Bold.otf
    - family: Calibre-Semibold
      fonts:
        - asset: fonts/Calibre Semibold.otf
    - family: CustomIcons
      fonts:
        - asset: fonts/custom_icons.ttf
    - family: Nexa-Bold
      fonts:
        - asset: fonts/Nexa-Bold.otf
    - family: Nexa-Light
      fonts:
        - asset: fonts/Nexa-Light.otf
    - family: Montserrat-B
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
    - family: Montserrat-M
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
    - family: Montserrat-R
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Montserrat-L
      fonts:
        - asset: fonts/Montserrat-Light.ttf
    - family: CM Sans Serif
      fonts:
        - asset: fonts/cm_sans_serif_2012.ttf
    - family: Poppins-B
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-M
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: Social
      fonts:
        - asset: fonts/SocialIcons.ttf
    - family: Roboto-L
      fonts:
        - asset: fonts/Roboto-Light.ttf
    - family: BackIcon
      fonts:
        - asset: fonts/back_icon.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
